What is a Python library? Why ^o we use Python libraries?

What is the difference between Numpy array and List?

3. Fin^ the shape, size an^ ^imension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [1]:
import numpy as np
arr= [[1, 2, 3, 4]
     ,[5, 6, 7, 8],
     [9, 10, 11, 12]]


In [2]:
array = np.array ( [ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


In [3]:
print(array.shape)
print(array.size)
print(array.ndim)

(3, 4)
12
2


4. Write python co^e to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [4]:
array = np.array ( [ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


In [5]:
first_row = array[0]
print(array[0])

[1 2 3 4]


5. How do you access the element at the thir^ row an^ fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [6]:
array = np.array ( [ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
element = array[2, 3]
print(element) 


12


6. Write code to extract all o^^-in^exe^ elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [7]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
b = a[1::2, 0::2]
print(b)

[[5 7]]


7. How can you generate a random 3x3 matrix with values between 0 an^ 1?

In [8]:
m = np.random.rand (3, 3)
print(m)

[[0.51358756 0.70958744 0.5505603 ]
 [0.75668003 0.4914207  0.91801524]
 [0.17379169 0.13514453 0.25497345]]


Describe the difference between np.random.rand and np.random.randn?

9. Write co^e to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [9]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
b = np.expand_dims(a, axis=-1)
print(b.shape)

(3, 4, 1)


10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [10]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
b = np.transpose(a)
c = a.T # use the .T attribute
print(b) 
print(c)


[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


11. Consider the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

In [11]:
import numpy as np
A2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
# using the * operator
result = A2*B2
print(result)

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [12]:
result = A2 + B2
print(result)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [13]:
result = A2 / B2
print(result)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
result = A2 - B2
print(result)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [15]:
result = A2 @ B2
print(result)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

12. Which function in Numpy can be used to swap the byte or^er of an array?

13. What is the significance of the np.linalg.inv function?

14. What does the np.reshape function do, and how is it use^?

15. What is broadcasting in Numpy?